services:

  backend:
    depends_on:
    - db
    - redis
    build: ./img_backend/.
    command: flask run --host=0.0.0.0
    restart: always
    ports:
    - 8083:5000
    volumes:
    - $PWD/img_backend/:/python-flask/
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      REDIS_AUTH: 'ComplexPa55word1'

  db:
    image: mysql
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  redis:
    image: redis:alpine
    command: "redis-server --requirepass ComplexPa55word1"
    ports:
    - 6379
    volumes:
    - $PWD/img_redis/redis-data:/var/lib/redis
    - $PWD/img_redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
    - REDIS_REPLICATION_MODE=master
      #    networks:
      #node_net:
      #  ipv4_address: 172.28.1.10

networks:
  node_net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16

volumes:
  db_data: {}
